# job name

#PBS -N pbstracker_test4
#PBS -S /bin/bash
#PBS -e /tmp/realtest4_err.log
#PBS -o /tmp/realtest4_out.log

# Resources
#PBS -l nodes=1:ppn=20
#PBS -l walltime=0:05:00

# Submit to this queue
#PBS -q debug

echo "This job has specified output and error files."

echo "The job has started. Current time: $(date)"

sleep 120 # within walltime

>&2 echo "This job has stderr output."

echo "The job has finished. Current time: $(date)"
